"""Add material_type back to StudyMaterial

Revision ID: 2ccd2b6c19ca
Revises: a4d0311dce58
Create Date: 2024-09-23 22:38:04.461463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ccd2b6c19ca'
down_revision = 'a4d0311dce58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('material_type', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_material', schema=None) as batch_op:
        batch_op.drop_column('material_type')

    # ### end Alembic commands ###
